M48
; DRILL file {KiCad 9.0.4} date 2025-09-28T14:36:28-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-28T14:36:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X19.11Y-20.605
X24.89Y-20.605
T2
X42.5Y-16.67
X47.5Y-16.67
M30
